baseURL = "/"
languageCode = "en-us"
title = "prenerLab"
theme = "kube"
description = ""
Paginate = 4

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  RSSLink = "/index.xml"
  author = "" # add your company name
  github = "chris-prener" # add your github profile name
  twitter = "chrisprener" # add your twitter profile
  email = "chris.prener@slu.edu"

[[menu.main]]
    name = "Docs"
    weight = 20
    url = "/docs/"
[[menu.main]]
    name = "Meta"
    weight = 10
    url = "/blog/"
[[menu.main]]
    name = "FAQ"
    weight = 30
    url = "/faq/"
[[menu.main]]
    name = "Tools"
    weight = 40
    url = "/tools/"
[[menu.main]]
    name = "License"
    weight = 50
    url = "/license/"